import type { ImageLibraryItem } from '@prisma/client';
import { NoProviderAvailableError, ProviderError } from '../../errors';
import { ingestImage } from '../images/ingest';
import { embedMissing, libraryDepsFrom, searchLibrary } from '../images/library';
import type { StockHit } from '../images/stock';
import type { PlanTier } from '../providers/router';
import { MIN_SIMILARITY } from '../slideshow/populate';
import type { PipelineDeps } from './deps';

// BACKLOG 15.B5 — IMAGE_STILL shots use the business's image library first (A6.5: "the router
// queries the image library before falling to DALL-E 3"; A6.3: "Every generated image is stored
// in the library so it can be reused"), and the buildable half of 15.W6 (A11.4: a generation
// refusal "falls back to … the closest stock match"):
//   1. pgvector search of the library with the shot's scene description; the best stored match
//      at or above the slideshow threshold (populate.ts MIN_SIMILARITY = 0.30) is used as-is;
//   2. otherwise the image is generated as before and then ingested with source GENERATED;
//   3. a generator refusal (content_policy) tries the configured stock sources for the scene.
// The library steps are best-effort: an embedding outage is a miss, never a failed shot.

export interface StillScope {
  organisationId: string;
  businessId: string;
  planTier: PlanTier;
}

function isBestEffortMiss(err: unknown): boolean {
  return err instanceof NoProviderAvailableError || err instanceof ProviderError;
}

/** The best stored library image for the query, or null (miss / search unavailable). */
export async function findLibraryStill(
  deps: PipelineDeps,
  scope: StillScope,
  query: string,
): Promise<ImageLibraryItem | null> {
  const text = query.trim();
  if (!text) return null;
  let hits: Awaited<ReturnType<typeof searchLibrary>>;
  try {
    hits = await searchLibrary(libraryDepsFrom(deps), scope, text, 8);
  } catch (err) {
    if (!isBestEffortMiss(err)) throw err;
    deps.logger.warn(
      { err: (err as Error).message },
      'image library search unavailable; generating',
    );
    return null;
  }
  const good = hits.filter((h) => h.similarity >= MIN_SIMILARITY);
  if (good.length === 0) return null;
  const items = await deps.db.imageLibraryItem.findMany({
    where: {
      id: { in: good.map((h) => h.id) },
      organisationId: scope.organisationId,
      // Hotlink-only stock (Unsplash) has no stored copy and cannot be composed.
      NOT: { s3Key: '' },
    },
  });
  const byId = new Map(items.map((i) => [i.id, i]));
  const best = good.map((h) => byId.get(h.id)).find((i): i is ImageLibraryItem => Boolean(i));
  if (!best) return null;
  return deps.db.imageLibraryItem.update({
    where: { id: best.id },
    data: { useCount: { increment: 1 }, lastUsedAt: new Date(deps.now()) },
  });
}

/** Keep a generated shot image in the library (A6.3). Non-fatal: returns the library id or null. */
export async function keepGeneratedStill(
  deps: PipelineDeps,
  scope: StillScope,
  input: { bucket: string; key: string; prompt: string; providerId: string },
): Promise<string | null> {
  try {
    const size = await deps.storage.size(input.bucket, input.key);
    const bytes = await deps.storage.readRange(input.bucket, input.key, 0, size - 1);
    const outcome = await ingestImage(libraryDepsFrom(deps), {
      organisationId: scope.organisationId,
      businessId: scope.businessId,
      source: 'GENERATED',
      sourceProvider: input.providerId,
      bytes,
      altText: input.prompt.slice(0, 500),
      generatedFromPrompt: input.prompt,
      licenseNotes: `Generated by ${input.providerId} for a video shot`,
    });
    if (outcome.status === 'skipped') return null;
    await embedNew(deps, scope);
    return outcome.id;
  } catch (err) {
    deps.logger.warn({ err: (err as Error).message }, 'generated still not added to the library');
    return null;
  }
}

/** Embed the new row so the next shot's library search can find it (best effort). */
async function embedNew(deps: PipelineDeps, scope: StillScope): Promise<void> {
  try {
    await embedMissing(libraryDepsFrom(deps), scope, 5);
  } catch (err) {
    if (!isBestEffortMiss(err)) throw err;
    deps.logger.warn({ err: (err as Error).message }, 'library image not embedded yet');
  }
}

/** A generator refusal (policy) — the only failure that falls back to stock. */
export function isGenerationRefusal(err: unknown): boolean {
  return err instanceof ProviderError && err.errorClass === 'content_policy';
}

function orientationOf(aspectRatio: string): 'landscape' | 'portrait' | 'square' {
  if (aspectRatio === '16:9') return 'landscape';
  if (aspectRatio === '1:1') return 'square';
  return 'portrait';
}

/** 15.W6 buildable half: the closest storable stock image for the scene, ingested as STOCK. */
export async function stockStillForRefusal(
  deps: PipelineDeps,
  scope: StillScope & { projectId: string },
  input: { query: string; aspectRatio: string },
): Promise<ImageLibraryItem | null> {
  const { primary, fallback } = deps.scan.stock();
  const ids = { userId: scope.organisationId, projectId: scope.projectId };
  for (const source of [...primary, ...fallback]) {
    let hits: StockHit[];
    try {
      hits = await source.search({
        query: input.query.slice(0, 100),
        perPage: 5,
        orientation: orientationOf(input.aspectRatio),
        ...ids,
      });
    } catch (err) {
      deps.logger.warn(
        { provider: source.provider, err: (err as Error).message },
        'stock search failed',
      );
      continue;
    }
    for (const hit of hits.filter((h) => h.storable)) {
      const outcome = await ingestImage(libraryDepsFrom(deps), {
        organisationId: scope.organisationId,
        businessId: scope.businessId,
        source: 'STOCK',
        sourceUrl: hit.pageUrl ?? hit.imageUrl,
        sourceProvider: hit.provider,
        downloadUrl: await source.downloadUrl(hit, ids),
        altText: hit.alt,
        tags: [],
        licenseNotes: `Stock (${hit.provider}) used after an image generation refusal`,
      }).catch(() => null);
      if (outcome && outcome.status !== 'skipped') {
        const item = await deps.db.imageLibraryItem.findFirst({
          where: { id: outcome.id, organisationId: scope.organisationId, NOT: { s3Key: '' } },
        });
        if (item) {
          await embedNew(deps, scope);
          return item;
        }
      }
    }
  }
  return null;
}
