import { LINKEDIN_VERSION } from '../platforms/linkedin';
import { DEFAULT_GRAPH_VERSION } from '../platforms/meta';
import { PLATFORM_RULES } from '../platforms/rules';
import { PLATFORMS } from '../services/catalog';

// BACKLOG 15.E4 — spec 18.1: "The engineering team must maintain a compliance matrix documenting
// current scope, quota, and review status per platform. Update at every API version change."
// ops/compliance-matrix.md is GENERATED from this file plus PLATFORM_RULES and the API versions
// the publishers use, and src/lib/studio/compliance/matrix.test.ts fails when the checked-in file
// is stale. Regenerate with:  npx tsx scripts/ops/compliance-matrix.ts
// Review status comes from CLAUDE.md "Provider credentials status" (operator-confirmed);
// scopes are the ones Studio's OAuth clients request (platforms/oauth.ts) or, for Meta, the
// permissions the Graph publishing endpoints document (Engagement holds the tokens).

export interface ConnectionCompliance {
  api: string;
  version: string;
  scopes: string;
  quota: string;
  reviewStatus: string;
  docs: string;
}

export const CONNECTIONS: Record<string, ConnectionCompliance> = {
  tiktok: {
    api: 'TikTok Content Posting API (open.tiktokapis.com/v2)',
    version: 'v2',
    scopes: 'user.info.basic, video.publish, video.list',
    quota: 'Per-creator daily post cap returned by creator_info; Direct Post needs video.publish',
    reviewStatus: 'Content Posting API approved (operator, CLAUDE.md)',
    docs: 'https://developers.tiktok.com/doc/content-posting-api-get-started',
  },
  instagram: {
    api: 'Instagram Graph API content publishing (graph.facebook.com)',
    version: DEFAULT_GRAPH_VERSION,
    scopes: 'instagram_basic, instagram_content_publish (Engagement-held tokens)',
    quota: 'content_publishing_limit: posts per rolling 24 h per account',
    reviewStatus: 'Meta App Review addition approved (operator, CLAUDE.md)',
    docs: 'https://developers.facebook.com/docs/instagram-platform/instagram-graph-api/reference/ig-user/media',
  },
  facebook: {
    api: 'Facebook Pages video / video_reels (graph.facebook.com)',
    version: DEFAULT_GRAPH_VERSION,
    scopes: 'pages_show_list, pages_read_engagement, pages_manage_posts (Engagement-held tokens)',
    quota: 'Graph API rate limits per Page (error 613)',
    reviewStatus: 'Meta App Review addition approved (operator, CLAUDE.md)',
    docs: 'https://developers.facebook.com/docs/graph-api/reference/page/videos/',
  },
  youtube: {
    api: 'YouTube Data API v3 (videos.insert, thumbnails.set, captions.insert)',
    version: 'v3',
    scopes: 'youtube.force-ssl, yt-analytics.readonly',
    quota: 'Daily units (videos.insert 1600 historically; quota increase requested per spec 18.1)',
    reviewStatus: 'Quota increase approved (operator, CLAUDE.md)',
    docs: 'https://developers.google.com/youtube/v3/determine_quota_cost',
  },
  linkedin: {
    api: 'LinkedIn Posts + Videos API (Community Management)',
    version: LINKEDIN_VERSION,
    scopes: 'openid, profile, w_member_social (+ r_member_postAnalytics when enabled)',
    quota: 'Per-member and per-application daily limits (LinkedIn rate limits)',
    reviewStatus: 'Marketing Developer Platform approved (operator, CLAUDE.md)',
    docs: 'https://learn.microsoft.com/en-us/linkedin/marketing/community-management/shares/videos-api',
  },
  x: {
    api: 'X API v2 (media upload + posts)',
    version: '2',
    scopes: 'tweet.read, tweet.write, users.read, media.write, offline.access',
    quota: 'Basic tier monthly post cap (spec 18.1: Basic for low volume, Pro for scale)',
    reviewStatus: 'Basic tier active (operator, CLAUDE.md)',
    docs: 'https://docs.x.com/x-api/fundamentals/rate-limits',
  },
};

const MB = 1024 * 1024;

function size(bytes: number): string {
  return bytes >= 1024 * MB ? `${bytes / (1024 * MB)} GB` : `${Math.round(bytes / MB)} MB`;
}

/** The whole Markdown document (deterministic: no dates, so the CI check is stable). */
export function renderComplianceMatrix(): string {
  const destinations = PLATFORMS.map((p) => {
    const r = PLATFORM_RULES[p];
    return `| ${p} | ${r.connectionPlatform} | ${r.credentials === 'meta' ? 'Engagement (Meta)' : 'Studio OAuth'} | ${r.aspectRatios.join(', ')} | ${r.minDurationSec}–${r.maxDurationSec} s | ${size(r.maxBytes)} | ${r.captionMaxChars}${r.captionLimitInBytes ? ' bytes' : ''} | ${r.maxHashtags} |`;
  });
  const connections = Object.entries(CONNECTIONS).map(
    ([key, c]) =>
      `| ${key} | ${c.api} | ${c.version} | ${c.scopes} | ${c.quota} | ${c.reviewStatus} | ${c.docs} |`,
  );
  return [
    '# Platform compliance matrix',
    '',
    '<!-- GENERATED by scripts/ops/compliance-matrix.ts from src/lib/studio/compliance/matrix.ts and',
    '     src/lib/studio/platforms/rules.ts. Do not edit by hand; CI fails when this file is stale. -->',
    '',
    'Spec 18.1: current scope, quota and review status per platform. Update at every API version',
    'change (bump the version constant in the publisher, then regenerate this file).',
    '',
    '## Connections (API, version, scopes, quota, review status)',
    '',
    '| Connection | API | Version | Scopes | Quota | Review status | Docs |',
    '| --- | --- | --- | --- | --- | --- | --- |',
    ...connections,
    '',
    '## Destinations (Studio publishing rules)',
    '',
    '| Destination | Connection | Credentials | Aspect ratios | Duration | Max file | Caption limit | Max hashtags |',
    '| --- | --- | --- | --- | --- | --- | --- | --- |',
    ...destinations,
    '',
  ].join('\n');
}
