import type { NotBuiltItem } from './not-built-types';

// Admin, automation, pipeline, cost, infrastructure and GATE 12 items not built or not run.
// Sources: PROGRESS.md (GATE 12 list, Operator decisions "NOT BUILT" notes, phase review lists),
// BACKLOG.md unchecked items (9.2, 9.3, 12.2, 12.3, 12.5), runbooks/*.md GAP lines.

export const PLATFORM_GAPS: NotBuiltItem[] = [
  // ------------------------------------------------------------------ Admin Centre
  {
    id: 'admin-health',
    group: 'Admin Centre',
    title: 'Queue health and provider health',
    blocker: 'missing endpoint',
    why: 'No admin API exposes queue depths or breaker states (they exist only as Prometheus metrics, and breakers are per process); the Admin Centre footnotes this.',
    source: 'PROGRESS [10.11]; admin-centre.tsx',
    plan: {
      screens: [
        'Admin → Queues (depth, failed, oldest waiting) and Providers (breaker, error rate, spend today)',
      ],
      endpoints: [
        'GET /api/studio/admin/queues',
        'GET /api/studio/admin/providers (needs Redis-backed breaker state)',
      ],
      days: 3,
      dependsOn: 'Redis-backed circuit breaker (below)',
    },
  },
  {
    id: 'safety-queue',
    group: 'Admin Centre',
    title: 'Content-safety review queue',
    blocker: 'missing endpoint',
    why: 'Script-safety REVIEW and content-safety REVIEW results stop the run (fail closed) because there is no human review queue (spec 16.4).',
    source: 'PROGRESS Phase 3 review list, [10.11]',
    plan: {
      screens: ['Admin → Safety review: item, reason, preview, Allow / Block with note'],
      endpoints: [
        'migration: safety_reviews',
        'GET /api/studio/admin/safety-reviews',
        'POST /api/studio/admin/safety-reviews/:id/decision (studio:admin:moderation) → resume run',
      ],
      days: 5,
      dependsOn: 'Trust & Safety process (who reviews, SLA)',
    },
  },
  {
    id: 'org-auto-approve-policy',
    group: 'Admin Centre',
    title: 'Per-organisation auto-approve policy',
    blocker: 'not started',
    why: 'Auto-approve is set per project (reviewPolicy) or by a template; there is no organisation-level policy for staff to set.',
    source: 'runbooks/review-publish-automation.md GAP',
    plan: {
      screens: ['Admin → Organisation policy'],
      endpoints: ['GET|PUT /api/studio/admin/organisations/:id/policy', 'migration: org_policies'],
      days: 2,
      dependsOn: 'none',
    },
  },
  // ------------------------------------------------------------------ Publishing and automation
  {
    id: 'meta-purge',
    group: 'Publishing and automation',
    title: 'Organisation purge endpoint for Meta channels',
    blocker: 'missing endpoint',
    why: 'Engagement has /internal/organisations/:id/purge; Studio has no counterpart, so deleting an organisation does not wipe its Instagram/Facebook channels.',
    source: 'PROGRESS [OPS-meta] NOT BUILT',
    plan: {
      screens: [],
      endpoints: [
        'POST /api/studio/internal/organisations/:id/purge (X-Service-Token; wipe tokens, disconnect, audit)',
      ],
      days: 1.5,
      dependsOn: 'Core calls it on organisation deletion',
    },
  },
  {
    id: 'meta-reconcile',
    group: 'Publishing and automation',
    title: 'Core ↔ Studio channel reconciliation and account-status check',
    blocker: 'not started',
    why: 'A missed DELETE leaves a channel active until Meta refuses its token; the daily account-status check is not built either.',
    source: 'runbooks/platform-account-revocation.md GAPs',
    plan: {
      screens: ['Connections: “last checked” per account'],
      endpoints: [
        'daily reconcile job against a Core channel list',
        'daily account-status job per platform',
      ],
      days: 3,
      dependsOn: 'Core: list-channels endpoint',
    },
  },
  {
    id: 'hive-async',
    group: 'Publishing and automation',
    title: 'Hive async moderation callback (videos > 90 s)',
    blocker: 'missing endpoint',
    why: 'Hive’s sync API handles ≤ 90 s; longer videos fail the content-safety check (fail closed), so long-form YouTube (4–8 min) cannot reach review.',
    source: 'PROGRESS Phase 3 review list',
    plan: {
      screens: [],
      endpoints: [
        'submit via Hive async task API',
        'POST /api/studio/webhooks/hive (signed callback) → resume run-quality-gate',
      ],
      days: 3,
      dependsOn: 'a public callback URL for Hive',
    },
  },
  {
    id: 'auto-publish-outbox',
    group: 'Publishing and automation',
    title: 'Auto-publish outbox and retry',
    blocker: 'not started',
    why: 'Approval and auto-publish are two steps without an outbox: if the process dies between them the project is APPROVED and nothing is posted.',
    source: 'runbooks/review-publish-automation.md GAP',
    plan: {
      screens: ['Review: “Auto-publish pending / failed — retry”'],
      endpoints: [
        'outbox rows written in the approval transaction',
        'outbox dispatcher job with retry',
      ],
      days: 2,
      dependsOn: 'none',
    },
  },
  {
    id: 'platform-canary',
    group: 'Publishing and automation',
    title: 'Daily per-platform adapter canary',
    blocker: 'blocked on a dependency',
    why: 'A daily run of the publisher tests against each platform’s sandbox account is not wired into CI; it needs sandbox credentials.',
    source: 'runbooks/platform-api-change.md GAP; GATE 12 list',
    plan: {
      screens: [],
      endpoints: ['scheduled CI workflow per platform + alert on failure'],
      days: 2,
      dependsOn: 'sandbox/test accounts per platform',
    },
  },
  // ------------------------------------------------------------------ Pipeline and media
  {
    id: 'sfx',
    group: 'Pipeline and media',
    title: 'Sound effects (SFX)',
    blocker: 'not started',
    why: 'Layer 5 builds background music only; SFX from the Storyblocks catalogue, MusicGen/Storyblocks music fallbacks and per-shot ducking are not built.',
    source: 'PROGRESS [OPS-music] NOT BUILT',
    plan: {
      screens: ['Review: music/SFX panel'],
      endpoints: ['Storyblocks audio adapter', 'SFX cues from Layer 2 shot list → EDL audio clips'],
      days: 4,
      dependsOn: 'Storyblocks API key',
    },
  },
  {
    id: 'fallback-adapters',
    group: 'Pipeline and media',
    title: 'Fallback provider adapters',
    blocker: 'not started',
    why: 'Only Runway is configured for AI clips (plus OpenAI images, ElevenLabs, Shotstack, Hive). Luma, Kling, Veo, fal, Replicate, HeyGen, D-ID, Storyblocks, Pexels footage, Azure Speech, Creatomate and Sightengine are router candidates without adapters, so an open Runway breaker leaves NO_PROVIDER_AVAILABLE.',
    source: 'PROGRESS GATE 2 review list; providers/router.ts',
    plan: {
      screens: [],
      endpoints: ['one adapter per provider implementing ProviderAdapter + cost estimate'],
      days: 18,
      dependsOn: 'provider accounts and keys (≈ 1.5 days each)',
    },
  },
  {
    id: 'loudness',
    group: 'Pipeline and media',
    title: 'Loudness normalisation and H.264 Baseline re-encode',
    blocker: 'not started',
    why: 'Renders outside −18…−10 LUFS go to QUALITY_FAILED (force-approvable) because the pipeline does not normalise; Baseline profile is not enforced for the same reason.',
    source: 'PROGRESS Phase 3 review list',
    plan: {
      screens: [],
      endpoints: ['ffmpeg loudnorm + re-encode step after compose'],
      days: 2,
      dependsOn: 'none',
    },
  },
  // ------------------------------------------------------------------ Cost controls
  {
    id: 'org-cap-overrides',
    group: 'Cost controls',
    title: 'Per-organisation cost cap overrides',
    blocker: 'not started',
    why: 'Caps are per plan tier only; there is no exception list for one organisation.',
    source: 'PROGRESS [OPS-caps]; runbooks/cost-runaway.md GAPs',
    plan: {
      screens: ['Admin → Cost report: “Override caps” per organisation'],
      endpoints: ['migration: org_cost_caps', 'PUT /api/studio/admin/organisations/:id/cost-caps'],
      days: 2,
      dependsOn: 'none',
    },
  },
  {
    id: 'auto-resume',
    group: 'Cost controls',
    title: 'Auto-resume of paused projects',
    blocker: 'not started',
    why: 'A paused project fails with cost_cap_paused and must be regenerated by hand; it does not resume at the day or month rollover.',
    source: 'PROGRESS [OPS-caps]; runbooks/cost-runaway.md GAPs',
    plan: {
      screens: ['Review: “Resumes automatically at 00:00 UTC” with opt-out'],
      endpoints: [
        'rollover job re-driving org_daily / org_monthly pauses (reuse services/redrive.ts)',
      ],
      days: 2,
      dependsOn: 'none',
    },
  },
  {
    id: 'cost-regression',
    group: 'Cost controls',
    title: 'Weekly cost regression test',
    blocker: 'not started',
    why: 'Spec 17.5’s weekly cost regression run is not scheduled.',
    source: 'runbooks/cost-runaway.md GAPs',
    plan: {
      screens: [],
      endpoints: ['scheduled CI job with the golden harness prices'],
      days: 1,
      dependsOn: 'none',
    },
  },
  // ------------------------------------------------------------------ Infrastructure
  {
    id: 'cdn-signed',
    group: 'Infrastructure',
    title: 'CDN signed URLs',
    blocker: 'blocked on a dependency',
    why: 'Previews and downloads are S3 presigned URLs; CloudFront signed URLs (CDN_URL) are not wired.',
    source: 'PROGRESS Phase 4 review list',
    plan: {
      screens: [],
      endpoints: ['CloudFront signer in storage.ts behind the same interface'],
      days: 2,
      dependsOn: 'CloudFront distribution + key pair',
    },
  },
  {
    id: 's3-lifecycle',
    group: 'Infrastructure',
    title: 'S3 lifecycle rules',
    blocker: 'needs people',
    why: 'Lifecycle and version-expiry rules live in the infrastructure repo and are not verified by code here.',
    source: 'runbooks/storage-cost.md GAP; GATE 12 list',
    plan: {
      screens: [],
      endpoints: ['lifecycle policy in infrastructure-as-code, linked from the runbook'],
      days: 1,
      dependsOn: 'DevOps',
    },
  },
  {
    id: 'redis-breaker',
    group: 'Infrastructure',
    title: 'Shared (Redis-backed) circuit breaker state',
    blocker: 'not started',
    why: 'Breaker state is per process, so each worker learns about an outage separately.',
    source: 'PROGRESS [2.10], Phase 11 review list',
    plan: {
      screens: [],
      endpoints: ['Redis store for circuit-breaker.ts'],
      days: 2,
      dependsOn: 'none',
    },
  },
  // ------------------------------------------------------------------ Staging and people (GATE 12)
  {
    id: 'rehearsals',
    group: 'Staging and people (GATE 12)',
    title: 'Kill-switch and rollback rehearsals',
    blocker: 'needs staging',
    why: 'Tooling and procedures are built (rehearse-kill-switch.ts, runbooks/rollback.md); the timed runs against the 60 s and 5 min SLOs have not happened.',
    source: 'BACKLOG 12.2, 12.3',
    plan: {
      screens: [],
      endpoints: ['run on staging; record timings in PROGRESS.md'],
      days: 1,
      dependsOn: 'staging environment with workers under load',
    },
  },
  {
    id: 'k6',
    group: 'Staging and people (GATE 12)',
    title: 'k6 smoke + full run and queue-throughput target',
    blocker: 'needs staging',
    why: 'load-test/k6/studio-api.js is ready; it has never been run, and alert thresholds wait on its results.',
    source: 'PROGRESS GATE 12 list; runbooks/README.md GAP',
    plan: {
      screens: [],
      endpoints: ['run smoke then full; tune StudioQueueBacklog / failure-rate thresholds'],
      days: 1,
      dependsOn: 'staging + a load-test organisation JWT',
    },
  },
  {
    id: 'pitr',
    group: 'Staging and people (GATE 12)',
    title: 'Point-in-time restore drill',
    blocker: 'needs staging',
    why: 'The backup/recovery runbook exists; no PITR restore has been rehearsed.',
    source: 'PROGRESS GATE 12 list',
    plan: {
      screens: [],
      endpoints: ['restore drill per runbooks/backup-recovery.md; record RTO/RPO'],
      days: 1,
      dependsOn: 'staging database with PITR enabled',
    },
  },
  {
    id: 'live-providers',
    group: 'Staging and people (GATE 12)',
    title: 'Live provider and posting runs',
    blocker: 'needs staging',
    why: 'Every provider and publisher is tested against documented contracts and fakes; live runs (npm run gate2:* / gate3, a real post per platform, first live Shotstack font check) are the operator’s.',
    source: 'PROGRESS GATE 2, 3, 5, 8',
    plan: {
      screens: [],
      endpoints: ['run with staging keys and one test account per platform'],
      days: 2,
      dependsOn: 'staging keys, platform test accounts, hosted fonts (STUDIO_FONTS_BASE_URL)',
    },
  },
  {
    id: 'corpus-runs',
    group: 'Staging and people (GATE 12)',
    title: 'Corpus sample run (9.2) and full run (9.3)',
    blocker: 'needs people',
    why: 'Unblocked (no licence needed), tooling ready; the 100-video sample needs operator review before the 50k run, which needs ENTERPRISE caps and more library workers.',
    source: 'BACKLOG 9.2, 9.3; runbooks/corpus-ingestion.md',
    plan: {
      screens: [],
      endpoints: ['scripts/ops/ingest-corpus.ts --sample 100 --apply, review, then --apply'],
      days: 3,
      dependsOn: 'the corpus manifest; STUDIO_LIBRARY_PLAN_TIER=ENTERPRISE',
    },
  },
  {
    id: 'core-meta-wiring',
    group: 'Staging and people (GATE 12)',
    title: 'Core wiring for the Meta internal endpoints',
    blocker: 'needs people',
    why: 'Studio’s endpoints are ready; Core must call them as it calls Engagement’s, request publish + insights scopes, and add retry/alerting for failed calls.',
    source: 'PROGRESS [OPS-meta] NOTE; runbooks/platform-account-revocation.md',
    plan: {
      screens: [],
      endpoints: ['Core: POST /internal/channels, DELETE, POST /internal/tokens/refreshed'],
      days: 3,
      dependsOn: 'Core team',
    },
  },
  {
    id: 'alerting-deploy',
    group: 'Staging and people (GATE 12)',
    title: 'Prometheus + Alertmanager deployment',
    blocker: 'needs people',
    why: 'Rules and routing are committed and CI-tested but not deployed; nothing has paged a human yet.',
    source: 'runbooks/README.md GAP; GATE 12 list',
    plan: {
      screens: [],
      endpoints: [
        'scrape jobs, rule file, Alertmanager with the PagerDuty key and Slack webhook files',
      ],
      days: 2,
      dependsOn: 'DevOps; PagerDuty service; #studio-alerts channel',
    },
  },
  {
    id: 'beta',
    group: 'Staging and people (GATE 12)',
    title: 'Beta onboarding, on-call rota, Trust & Safety audit',
    blocker: 'needs people',
    why: '5–10 friendly customers, an on-call rota and the monthly content-safety audit process are people work before the Go / No-Go.',
    source: 'BACKLOG 12.5; PROGRESS GATE 12 list; runbooks/content-safety-miss.md GAP',
    plan: {
      screens: [],
      endpoints: ['onboarding sessions, feedback log, rota, audit sampling'],
      days: 10,
      dependsOn: 'GA candidate on staging',
    },
  },
];
